Vagrant.configure("2") do |config|
  config.vm.box = "lucid64"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: "192.168.33.11"
end
